# Generated by Django 5.2.9 on 2026-06-27 05:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CardioSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('modality', models.CharField(choices=[('steady', 'Steady State'), ('hiit', 'HIIT'), ('sport', 'Sport')], max_length=20)),
                ('activity', models.CharField(max_length=100)),
                ('duration_minutes', models.PositiveSmallIntegerField()),
                ('distance_km', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('avg_heart_rate', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('max_heart_rate', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('avg_pace', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('pace_unit', models.CharField(blank=True, choices=[('min_per_km', 'min/km'), ('min_per_mile', 'min/mile')], max_length=20, null=True)),
                ('splits', models.JSONField(default=list)),
                ('zone_minutes', models.JSONField(default=dict)),
                ('zone_bounds', models.JSONField(blank=True, null=True)),
                ('perceived_exertion', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cardio_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('wger_id', models.IntegerField(blank=True, null=True)),
                ('primary_muscle', models.CharField(max_length=100)),
                ('secondary_muscles', models.JSONField(default=list)),
                ('category', models.CharField(choices=[('compound', 'Compound'), ('isolation', 'Isolation'), ('cardio', 'Cardio')], max_length=20)),
                ('equipment', models.CharField(max_length=100)),
                ('is_custom', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_exercises', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_type', models.CharField(choices=[('strength', 'Strength'), ('bodyweight', 'Bodyweight'), ('body_fat', 'Body Fat'), ('performance', 'Performance'), ('habit', 'Habit')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('target_mode', models.CharField(blank=True, choices=[('one_rm', 'One Rep Max'), ('weight_for_reps', 'Weight for Reps'), ('x_bodyweight', 'X Bodyweight')], max_length=20, null=True)),
                ('target_value', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('target_reps', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('target_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('target_bodyfat', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('baseline_value', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('achieved', 'Achieved'), ('abandoned', 'Abandoned')], default='active', max_length=20)),
                ('status_changed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exercise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goals', to='training.exercise')),
                ('superseded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supersedes', to='training.goal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NutritionTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_effective', models.DateField()),
                ('tdee', models.DecimalField(decimal_places=2, max_digits=7)),
                ('calorie_target', models.DecimalField(decimal_places=2, max_digits=7)),
                ('protein_g', models.DecimalField(decimal_places=2, max_digits=6)),
                ('carbs_g', models.DecimalField(decimal_places=2, max_digits=6)),
                ('fat_g', models.DecimalField(decimal_places=2, max_digits=6)),
                ('rationale', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_targets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_effective'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('goal', models.CharField(max_length=255)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('length_weeks', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('generating', 'Generating'), ('active', 'Active'), ('archived', 'Archived')], default='generating', max_length=20)),
                ('generation_task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('meta', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProgramDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.PositiveSmallIntegerField()),
                ('day_number', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('is_rest', models.BooleanField(default=False)),
                ('focus', models.CharField(blank=True, max_length=255)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='training.program')),
            ],
            options={
                'ordering': ['week_number', 'day_number'],
                'unique_together': {('program', 'week_number', 'day_number')},
            },
        ),
        migrations.CreateModel(
            name='ProgramExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('target_sets', models.PositiveSmallIntegerField()),
                ('target_reps_low', models.PositiveSmallIntegerField()),
                ('target_reps_high', models.PositiveSmallIntegerField()),
                ('target_rpe', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('target_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('notes', models.TextField(blank=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_exercises', to='training.exercise')),
                ('program_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='training.programday')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('duration_minutes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('chat', 'Chat'), ('import', 'Import')], default='manual', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('program_day', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='training.programday')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SessionSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_index', models.PositiveSmallIntegerField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=7)),
                ('reps', models.PositiveSmallIntegerField()),
                ('rpe', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('set_type', models.CharField(choices=[('working', 'Working'), ('warmup', 'Warmup'), ('backoff', 'Backoff'), ('dropset', 'Dropset'), ('failure', 'Failure')], default='working', max_length=20)),
                ('is_estimated', models.BooleanField(default=False)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_sets', to='training.exercise')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='training.session')),
            ],
            options={
                'ordering': ['set_index'],
            },
        ),
        migrations.CreateModel(
            name='BodyCompositionEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('body_fat_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('lean_mass', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('measurements', models.JSONField(default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='body_composition_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='BodyweightEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bodyweight_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='HeartRateEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('resting_hr', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('hrv', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('max_hr', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('import', 'Import')], default='manual', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heart_rate_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='WeeklyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('summary_markdown', models.TextField(blank=True)),
                ('metrics', models.JSONField(default=dict)),
                ('generation_task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-week_start'],
                'unique_together': {('user', 'week_start')},
            },
        ),
    ]
