# Generated by Django 5.2.9 on 2026-06-27 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardiosession',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
